; Auto-generated. Do not edit!


(in-package recyclerbot-msg)


;//! \htmlinclude GraspClientFeedback.msg.html

(defclass <GraspClientFeedback> (ros-message)
  ()
)
(defmethod serialize ((msg <GraspClientFeedback>) ostream)
  "Serializes a message object of type '<GraspClientFeedback>"
)
(defmethod deserialize ((msg <GraspClientFeedback>) istream)
  "Deserializes a message object of type '<GraspClientFeedback>"
  msg
)
(defmethod ros-datatype ((msg (eql '<GraspClientFeedback>)))
  "Returns string type for a message object of type '<GraspClientFeedback>"
  "recyclerbot/GraspClientFeedback")
(defmethod md5sum ((type (eql '<GraspClientFeedback>)))
  "Returns md5sum for a message object of type '<GraspClientFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(defmethod message-definition ((type (eql '<GraspClientFeedback>)))
  "Returns full string definition for message of type '<GraspClientFeedback>"
  (format nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback definition~%~%~%"))
(defmethod serialization-length ((msg <GraspClientFeedback>))
  (+ 0
))
(defmethod ros-message-to-list ((msg <GraspClientFeedback>))
  "Converts a ROS message object to a list"
  (list '<GraspClientFeedback>
))
