; Auto-generated. Do not edit!


(in-package recyclerbot-msg)


;//! \htmlinclude GraspClientGoal.msg.html

(defclass <GraspClientGoal> (ros-message)
  ((origin_row
    :reader origin_row-val
    :initarg :origin_row
    :type fixnum
    :initform 0)
   (origin_col
    :reader origin_col-val
    :initarg :origin_col
    :type fixnum
    :initform 0)
   (destination_row
    :reader destination_row-val
    :initarg :destination_row
    :type fixnum
    :initform 0)
   (destination_col
    :reader destination_col-val
    :initarg :destination_col
    :type fixnum
    :initform 0)
   (capture
    :reader capture-val
    :initarg :capture
    :type boolean
    :initform nil))
)
(defmethod serialize ((msg <GraspClientGoal>) ostream)
  "Serializes a message object of type '<GraspClientGoal>"
    (write-byte (ldb (byte 8 0) (slot-value msg 'origin_row)) ostream)
    (write-byte (ldb (byte 8 0) (slot-value msg 'origin_col)) ostream)
    (write-byte (ldb (byte 8 0) (slot-value msg 'destination_row)) ostream)
    (write-byte (ldb (byte 8 0) (slot-value msg 'destination_col)) ostream)
    (write-byte (ldb (byte 8 0) (if (slot-value msg 'capture) 1 0)) ostream)
)
(defmethod deserialize ((msg <GraspClientGoal>) istream)
  "Deserializes a message object of type '<GraspClientGoal>"
  (setf (ldb (byte 8 0) (slot-value msg 'origin_row)) (read-byte istream))
  (setf (ldb (byte 8 0) (slot-value msg 'origin_col)) (read-byte istream))
  (setf (ldb (byte 8 0) (slot-value msg 'destination_row)) (read-byte istream))
  (setf (ldb (byte 8 0) (slot-value msg 'destination_col)) (read-byte istream))
  (setf (slot-value msg 'capture) (not (zerop (read-byte istream))))
  msg
)
(defmethod ros-datatype ((msg (eql '<GraspClientGoal>)))
  "Returns string type for a message object of type '<GraspClientGoal>"
  "recyclerbot/GraspClientGoal")
(defmethod md5sum ((type (eql '<GraspClientGoal>)))
  "Returns md5sum for a message object of type '<GraspClientGoal>"
  "a89dc6763697b95e76194f808753f94e")
(defmethod message-definition ((type (eql '<GraspClientGoal>)))
  "Returns full string definition for message of type '<GraspClientGoal>"
  (format nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition~%int8 origin_row~%int8 origin_col~%int8 destination_row~%int8 destination_col~%bool capture~%~%~%~%"))
(defmethod serialization-length ((msg <GraspClientGoal>))
  (+ 0
     1
     1
     1
     1
     1
))
(defmethod ros-message-to-list ((msg <GraspClientGoal>))
  "Converts a ROS message object to a list"
  (list '<GraspClientGoal>
    (cons ':origin_row (origin_row-val msg))
    (cons ':origin_col (origin_col-val msg))
    (cons ':destination_row (destination_row-val msg))
    (cons ':destination_col (destination_col-val msg))
    (cons ':capture (capture-val msg))
))
