; Auto-generated. Do not edit!


(in-package recyclerbot-msg)


;//! \htmlinclude GraspClientActionGoal.msg.html

(defclass <GraspClientActionGoal> (ros-message)
  ((header
    :reader header-val
    :initarg :header
    :type roslib-msg:<Header>
    :initform (make-instance 'roslib-msg:<Header>))
   (goal_id
    :reader goal_id-val
    :initarg :goal_id
    :type actionlib_msgs-msg:<GoalID>
    :initform (make-instance 'actionlib_msgs-msg:<GoalID>))
   (goal
    :reader goal-val
    :initarg :goal
    :type recyclerbot-msg:<GraspClientGoal>
    :initform (make-instance 'recyclerbot-msg:<GraspClientGoal>)))
)
(defmethod serialize ((msg <GraspClientActionGoal>) ostream)
  "Serializes a message object of type '<GraspClientActionGoal>"
  (serialize (slot-value msg 'header) ostream)
  (serialize (slot-value msg 'goal_id) ostream)
  (serialize (slot-value msg 'goal) ostream)
)
(defmethod deserialize ((msg <GraspClientActionGoal>) istream)
  "Deserializes a message object of type '<GraspClientActionGoal>"
  (deserialize (slot-value msg 'header) istream)
  (deserialize (slot-value msg 'goal_id) istream)
  (deserialize (slot-value msg 'goal) istream)
  msg
)
(defmethod ros-datatype ((msg (eql '<GraspClientActionGoal>)))
  "Returns string type for a message object of type '<GraspClientActionGoal>"
  "recyclerbot/GraspClientActionGoal")
(defmethod md5sum ((type (eql '<GraspClientActionGoal>)))
  "Returns md5sum for a message object of type '<GraspClientActionGoal>"
  "c4c14d53c458c0d2f6e76127d09c67a8")
(defmethod message-definition ((type (eql '<GraspClientActionGoal>)))
  "Returns full string definition for message of type '<GraspClientActionGoal>"
  (format nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%Header header~%actionlib_msgs/GoalID goal_id~%GraspClientGoal goal~%~%================================================================================~%MSG: roslib/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.secs: seconds (stamp_secs) since epoch~%# * stamp.nsecs: nanoseconds since stamp_secs~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%# 0: no frame~%# 1: global frame~%string frame_id~%~%================================================================================~%MSG: actionlib_msgs/GoalID~%# The stamp should store the time at which this goal was requested.~%# It is used by an action server when it tries to preempt all~%# goals that were requested before a certain time~%time stamp~%~%# The id provides a way to associate feedback and~%# result message with specific goal requests. The id~%# specified must be unique.~%string id~%~%~%================================================================================~%MSG: recyclerbot/GraspClientGoal~%# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition~%int8 origin_row~%int8 origin_col~%int8 destination_row~%int8 destination_col~%bool capture~%~%~%~%"))
(defmethod serialization-length ((msg <GraspClientActionGoal>))
  (+ 0
     (serialization-length (slot-value msg 'header))
     (serialization-length (slot-value msg 'goal_id))
     (serialization-length (slot-value msg 'goal))
))
(defmethod ros-message-to-list ((msg <GraspClientActionGoal>))
  "Converts a ROS message object to a list"
  (list '<GraspClientActionGoal>
    (cons ':header (header-val msg))
    (cons ':goal_id (goal_id-val msg))
    (cons ':goal (goal-val msg))
))
