; Auto-generated. Do not edit!


(in-package recyclerbot-msg)


;//! \htmlinclude GraspGoal.msg.html

(defclass <GraspGoal> (ros-message)
  ((targetPose
    :reader targetPose-val
    :initarg :targetPose
    :type geometry_msgs-msg:<PoseStamped>
    :initform (make-instance 'geometry_msgs-msg:<PoseStamped>)))
)
(defmethod serialize ((msg <GraspGoal>) ostream)
  "Serializes a message object of type '<GraspGoal>"
  (serialize (slot-value msg 'targetPose) ostream)
)
(defmethod deserialize ((msg <GraspGoal>) istream)
  "Deserializes a message object of type '<GraspGoal>"
  (deserialize (slot-value msg 'targetPose) istream)
  msg
)
(defmethod ros-datatype ((msg (eql '<GraspGoal>)))
  "Returns string type for a message object of type '<GraspGoal>"
  "recyclerbot/GraspGoal")
(defmethod md5sum ((type (eql '<GraspGoal>)))
  "Returns md5sum for a message object of type '<GraspGoal>"
  "b184098acb98f59165420ef057956537")
(defmethod message-definition ((type (eql '<GraspGoal>)))
  "Returns full string definition for message of type '<GraspGoal>"
  (format nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# goal definition~%geometry_msgs/PoseStamped targetPose~%~%================================================================================~%MSG: geometry_msgs/PoseStamped~%# A Pose with reference coordinate frame and timestamp~%Header header~%Pose pose~%~%================================================================================~%MSG: roslib/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.secs: seconds (stamp_secs) since epoch~%# * stamp.nsecs: nanoseconds since stamp_secs~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%# 0: no frame~%# 1: global frame~%string frame_id~%~%================================================================================~%MSG: geometry_msgs/Pose~%# A representation of pose in free space, composed of postion and orientation. ~%Point position~%Quaternion orientation~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%================================================================================~%MSG: geometry_msgs/Quaternion~%# This represents an orientation in free space in quaternion form.~%~%float64 x~%float64 y~%float64 z~%float64 w~%~%~%"))
(defmethod serialization-length ((msg <GraspGoal>))
  (+ 0
     (serialization-length (slot-value msg 'targetPose))
))
(defmethod ros-message-to-list ((msg <GraspGoal>))
  "Converts a ROS message object to a list"
  (list '<GraspGoal>
    (cons ':targetPose (targetPose-val msg))
))
