; Auto-generated. Do not edit!


(in-package recyclerbot-msg)


;//! \htmlinclude GraspFeedback.msg.html

(defclass <GraspFeedback> (ros-message)
  ((currentPose
    :reader currentPose-val
    :initarg :currentPose
    :type geometry_msgs-msg:<Pose>
    :initform (make-instance 'geometry_msgs-msg:<Pose>)))
)
(defmethod serialize ((msg <GraspFeedback>) ostream)
  "Serializes a message object of type '<GraspFeedback>"
  (serialize (slot-value msg 'currentPose) ostream)
)
(defmethod deserialize ((msg <GraspFeedback>) istream)
  "Deserializes a message object of type '<GraspFeedback>"
  (deserialize (slot-value msg 'currentPose) istream)
  msg
)
(defmethod ros-datatype ((msg (eql '<GraspFeedback>)))
  "Returns string type for a message object of type '<GraspFeedback>"
  "recyclerbot/GraspFeedback")
(defmethod md5sum ((type (eql '<GraspFeedback>)))
  "Returns md5sum for a message object of type '<GraspFeedback>"
  "68f88dbab9859bab49fcc8cd2125bed2")
(defmethod message-definition ((type (eql '<GraspFeedback>)))
  "Returns full string definition for message of type '<GraspFeedback>"
  (format nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# feedback definition~%geometry_msgs/Pose currentPose~%~%~%================================================================================~%MSG: geometry_msgs/Pose~%# A representation of pose in free space, composed of postion and orientation. ~%Point position~%Quaternion orientation~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%================================================================================~%MSG: geometry_msgs/Quaternion~%# This represents an orientation in free space in quaternion form.~%~%float64 x~%float64 y~%float64 z~%float64 w~%~%~%"))
(defmethod serialization-length ((msg <GraspFeedback>))
  (+ 0
     (serialization-length (slot-value msg 'currentPose))
))
(defmethod ros-message-to-list ((msg <GraspFeedback>))
  "Converts a ROS message object to a list"
  (list '<GraspFeedback>
    (cons ':currentPose (currentPose-val msg))
))
