/* auto-generated by genmsg_cpp from /home/davidmandle/rospackages/cart_interp/msg/CartesianArmActionGoal.msg.  Do not edit! */
#ifndef CART_INTERP_CARTESIANARMACTIONGOAL_H
#define CART_INTERP_CARTESIANARMACTIONGOAL_H

#include <string>
#include <vector>
#include "ros/message.h"
#include "ros/debug.h"
#include "ros/assert.h"
#include "ros/time.h"

#include "roslib/Header.h"
#include "geometry_msgs/Point.h"
#include "geometry_msgs/Quaternion.h"
#include "geometry_msgs/Pose.h"
#include "geometry_msgs/PoseStamped.h"

namespace cart_interp
{

//! \htmlinclude CartesianArmActionGoal.msg.html

class CartesianArmActionGoal : public ros::Message
{
public:
  typedef boost::shared_ptr<CartesianArmActionGoal> Ptr;
  typedef boost::shared_ptr<CartesianArmActionGoal const> ConstPtr;

  typedef geometry_msgs::PoseStamped _setpoint_type;

  geometry_msgs::PoseStamped setpoint;

  CartesianArmActionGoal() : ros::Message()
  {
  }
  CartesianArmActionGoal(const CartesianArmActionGoal &copy) : ros::Message(),
    setpoint(copy.setpoint)
  {
    (void)copy;
  }
  CartesianArmActionGoal &operator =(const CartesianArmActionGoal &copy)
  {
    if (this == &copy)
      return *this;
    setpoint = copy.setpoint;
    return *this;
  }
  virtual ~CartesianArmActionGoal() 
  {
  }
  inline static std::string __s_getDataType() { return std::string("cart_interp/CartesianArmActionGoal"); }
  inline static std::string __s_getMD5Sum() { return std::string("7233d915b08b33dfe82d846f84b047b7"); }
  inline static std::string __s_getMessageDefinition()
  {
    return std::string(
    "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
    "# goal definition\n"
    "geometry_msgs/PoseStamped setpoint\n"
    "\n"
    "================================================================================\n"
    "MSG: geometry_msgs/PoseStamped\n"
    "# A Pose with reference coordinate frame and timestamp\n"
    "Header header\n"
    "Pose pose\n"
    "\n"
    "================================================================================\n"
    "MSG: roslib/Header\n"
    "# Standard metadata for higher-level stamped data types.\n"
    "# This is generally used to communicate timestamped data \n"
    "# in a particular coordinate frame.\n"
    "# \n"
    "# sequence ID: consecutively increasing ID \n"
    "uint32 seq\n"
    "#Two-integer timestamp that is expressed as:\n"
    "# * stamp.secs: seconds (stamp_secs) since epoch\n"
    "# * stamp.nsecs: nanoseconds since stamp_secs\n"
    "# time-handling sugar is provided by the client library\n"
    "time stamp\n"
    "#Frame this data is associated with\n"
    "# 0: no frame\n"
    "# 1: global frame\n"
    "string frame_id\n"
    "\n"
    "================================================================================\n"
    "MSG: geometry_msgs/Pose\n"
    "# A representation of pose in free space, composed of postion and orientation. \n"
    "Point position\n"
    "Quaternion orientation\n"
    "\n"
    "================================================================================\n"
    "MSG: geometry_msgs/Point\n"
    "# This contains the position of a point in free space\n"
    "float64 x\n"
    "float64 y\n"
    "float64 z\n"
    "\n"
    "================================================================================\n"
    "MSG: geometry_msgs/Quaternion\n"
    "# This represents an orientation in free space in quaternion form.\n"
    "\n"
    "float64 x\n"
    "float64 y\n"
    "float64 z\n"
    "float64 w\n"
    "\n"
    "\n"
    );
  }
  inline virtual const std::string __getDataType() const { return __s_getDataType(); }
  inline virtual const std::string __getMD5Sum() const { return __s_getMD5Sum(); }
  inline virtual const std::string __getMessageDefinition() const { return __s_getMessageDefinition(); }
  inline uint32_t serializationLength() const
  {
    unsigned __l = 0;
    __l += setpoint.serializationLength(); // setpoint
    return __l;
  }
  virtual uint8_t *serialize(uint8_t *write_ptr,
#if defined(__GNUC__)
                             __attribute__((unused)) uint32_t seq) const
#else
                             uint32_t seq) const
#endif
  {
    write_ptr = setpoint.serialize(write_ptr, seq);
    return write_ptr;
  }
  virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    read_ptr = setpoint.deserialize(read_ptr);
    return read_ptr;
  }
};

typedef boost::shared_ptr<CartesianArmActionGoal> CartesianArmActionGoalPtr;
typedef boost::shared_ptr<CartesianArmActionGoal const> CartesianArmActionGoalConstPtr;


}

#endif
