/* auto-generated by genmsg_cpp from /home/davidmandle/rospackages/cart_interp/msg/CartesianMoveRightArmActionResult.msg.  Do not edit! */
#ifndef CART_INTERP_CARTESIANMOVERIGHTARMACTIONRESULT_H
#define CART_INTERP_CARTESIANMOVERIGHTARMACTIONRESULT_H

#include <string>
#include <vector>
#include "ros/message.h"
#include "ros/debug.h"
#include "ros/assert.h"
#include "ros/time.h"

#include "roslib/Header.h"
#include "actionlib_msgs/GoalID.h"
#include "actionlib_msgs/GoalStatus.h"
#include "geometry_msgs/Point.h"
#include "geometry_msgs/Quaternion.h"
#include "geometry_msgs/Pose.h"
#include "cart_interp/CartesianMoveRightArmResult.h"

namespace cart_interp
{

//! \htmlinclude CartesianMoveRightArmActionResult.msg.html

class CartesianMoveRightArmActionResult : public ros::Message
{
public:
  typedef boost::shared_ptr<CartesianMoveRightArmActionResult> Ptr;
  typedef boost::shared_ptr<CartesianMoveRightArmActionResult const> ConstPtr;

  typedef roslib::Header _header_type;
  typedef actionlib_msgs::GoalStatus _status_type;
  typedef cart_interp::CartesianMoveRightArmResult _result_type;

  roslib::Header header;
  actionlib_msgs::GoalStatus status;
  cart_interp::CartesianMoveRightArmResult result;

  CartesianMoveRightArmActionResult() : ros::Message()
  {
  }
  CartesianMoveRightArmActionResult(const CartesianMoveRightArmActionResult &copy) : ros::Message(),
    header(copy.header),
    status(copy.status),
    result(copy.result)
  {
    (void)copy;
  }
  CartesianMoveRightArmActionResult &operator =(const CartesianMoveRightArmActionResult &copy)
  {
    if (this == &copy)
      return *this;
    header = copy.header;
    status = copy.status;
    result = copy.result;
    return *this;
  }
  virtual ~CartesianMoveRightArmActionResult() 
  {
  }
  inline static std::string __s_getDataType() { return std::string("cart_interp/CartesianMoveRightArmActionResult"); }
  inline static std::string __s_getMD5Sum() { return std::string("8796c700a48eebab32515e1356179491"); }
  inline static std::string __s_getMessageDefinition()
  {
    return std::string(
    "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
    "\n"
    "Header header\n"
    "actionlib_msgs/GoalStatus status\n"
    "CartesianMoveRightArmResult result\n"
    "\n"
    "================================================================================\n"
    "MSG: roslib/Header\n"
    "# Standard metadata for higher-level stamped data types.\n"
    "# This is generally used to communicate timestamped data \n"
    "# in a particular coordinate frame.\n"
    "# \n"
    "# sequence ID: consecutively increasing ID \n"
    "uint32 seq\n"
    "#Two-integer timestamp that is expressed as:\n"
    "# * stamp.secs: seconds (stamp_secs) since epoch\n"
    "# * stamp.nsecs: nanoseconds since stamp_secs\n"
    "# time-handling sugar is provided by the client library\n"
    "time stamp\n"
    "#Frame this data is associated with\n"
    "# 0: no frame\n"
    "# 1: global frame\n"
    "string frame_id\n"
    "\n"
    "================================================================================\n"
    "MSG: actionlib_msgs/GoalStatus\n"
    "GoalID goal_id\n"
    "uint8 status\n"
    "uint8 PENDING         = 0   # The goal has yet to be processed by the action server\n"
    "uint8 ACTIVE          = 1   # The goal is currently being processed by the action server\n"
    "uint8 PREEMPTED       = 2   # The goal received a cancel request after it started executing\n"
    "                            #   and has since completed its execution (Terminal State)\n"
    "uint8 SUCCEEDED       = 3   # The goal was achieved successfully by the action server (Terminal State)\n"
    "uint8 ABORTED         = 4   # The goal was aborted during execution by the action server due\n"
    "                            #    to some failure (Terminal State)\n"
    "uint8 REJECTED        = 5   # The goal was rejected by the action server without being processed,\n"
    "                            #    because the goal was unattainable or invalid (Terminal State)\n"
    "uint8 PREEMPTING      = 6   # The goal received a cancel request after it started executing\n"
    "                            #    and has not yet completed execution\n"
    "uint8 RECALLING       = 7   # The goal received a cancel request before it started executing,\n"
    "                            #    but the action server has not yet confirmed that the goal is canceled\n"
    "uint8 RECALLED        = 8   # The goal received a cancel request before it started executing\n"
    "                            #    and was successfully cancelled (Terminal State)\n"
    "uint8 LOST            = 9   # An action client can determine that a goal is LOST. This should not be\n"
    "                            #    sent over the wire by an action server\n"
    "\n"
    "#Allow for the user to associate a string with GoalStatus for debugging\n"
    "string text\n"
    "\n"
    "\n"
    "================================================================================\n"
    "MSG: actionlib_msgs/GoalID\n"
    "# The stamp should store the time at which this goal was requested.\n"
    "# It is used by an action server when it tries to preempt all\n"
    "# goals that were requested before a certain time\n"
    "time stamp\n"
    "\n"
    "# The id provides a way to associate feedback and\n"
    "# result message with specific goal requests. The id\n"
    "# specified must be unique.\n"
    "string id\n"
    "\n"
    "\n"
    "================================================================================\n"
    "MSG: cart_interp/CartesianMoveRightArmResult\n"
    "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
    "# result definition\n"
    "geometry_msgs/Pose endpoint\n"
    "\n"
    "================================================================================\n"
    "MSG: geometry_msgs/Pose\n"
    "# A representation of pose in free space, composed of postion and orientation. \n"
    "Point position\n"
    "Quaternion orientation\n"
    "\n"
    "================================================================================\n"
    "MSG: geometry_msgs/Point\n"
    "# This contains the position of a point in free space\n"
    "float64 x\n"
    "float64 y\n"
    "float64 z\n"
    "\n"
    "================================================================================\n"
    "MSG: geometry_msgs/Quaternion\n"
    "# This represents an orientation in free space in quaternion form.\n"
    "\n"
    "float64 x\n"
    "float64 y\n"
    "float64 z\n"
    "float64 w\n"
    "\n"
    "\n"
    );
  }
  inline virtual const std::string __getDataType() const { return __s_getDataType(); }
  inline virtual const std::string __getMD5Sum() const { return __s_getMD5Sum(); }
  inline virtual const std::string __getMessageDefinition() const { return __s_getMessageDefinition(); }
  inline uint32_t serializationLength() const
  {
    unsigned __l = 0;
    __l += header.serializationLength(); // header
    __l += status.serializationLength(); // status
    __l += result.serializationLength(); // result
    return __l;
  }
  virtual uint8_t *serialize(uint8_t *write_ptr,
                             uint32_t seq) const
  {
    roslib::Header _ser_header = header;
    bool __reset_seq = (header.seq == 0);
    if (__reset_seq) _ser_header.seq = seq;
    write_ptr = _ser_header.serialize(write_ptr, seq);
    write_ptr = status.serialize(write_ptr, seq);
    write_ptr = result.serialize(write_ptr, seq);
    return write_ptr;
  }
  virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    read_ptr = header.deserialize(read_ptr);
    read_ptr = status.deserialize(read_ptr);
    read_ptr = result.deserialize(read_ptr);
    return read_ptr;
  }
};

typedef boost::shared_ptr<CartesianMoveRightArmActionResult> CartesianMoveRightArmActionResultPtr;
typedef boost::shared_ptr<CartesianMoveRightArmActionResult const> CartesianMoveRightArmActionResultConstPtr;


}

#endif
