# autogenerated by genmsg_py from CartesianArmServerActionGoal.msg. Do not edit.
import roslib.message
import struct

import geometry_msgs.msg
import roslib.rostime
import cart_interp.msg
import roslib.msg
import actionlib_msgs.msg

class CartesianArmServerActionGoal(roslib.message.Message):
  _md5sum = "8188ffc0ebe10e91044960a5c85b373a"
  _type = "cart_interp/CartesianArmServerActionGoal"
  _has_header = True #flag to mark the presence of a Header object
  _full_text = """# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======

Header header
actionlib_msgs/GoalID goal_id
CartesianArmServerGoal goal

================================================================================
MSG: roslib/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.secs: seconds (stamp_secs) since epoch
# * stamp.nsecs: nanoseconds since stamp_secs
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id

================================================================================
MSG: actionlib_msgs/GoalID
# The stamp should store the time at which this goal was requested.
# It is used by an action server when it tries to preempt all
# goals that were requested before a certain time
time stamp

# The id provides a way to associate feedback and
# result message with specific goal requests. The id
# specified must be unique.
string id


================================================================================
MSG: cart_interp/CartesianArmServerGoal
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
# goal definition
geometry_msgs/PoseStamped setpoint

================================================================================
MSG: geometry_msgs/PoseStamped
# A Pose with reference coordinate frame and timestamp
Header header
Pose pose

================================================================================
MSG: geometry_msgs/Pose
# A representation of pose in free space, composed of postion and orientation. 
Point position
Quaternion orientation

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w

"""
  __slots__ = ['header','goal_id','goal']
  _slot_types = ['Header','actionlib_msgs/GoalID','cart_interp/CartesianArmServerGoal']

  ## Constructor. Any message fields that are implicitly/explicitly
  ## set to None will be assigned a default value. The recommend
  ## use is keyword arguments as this is more robust to future message
  ## changes.  You cannot mix in-order arguments and keyword arguments.
  ##
  ## The available fields are:
  ##   header,goal_id,goal
  ##
  ## @param self: self
  ## @param args: complete set of field values, in .msg order
  ## @param kwds: use keyword arguments corresponding to message field names
  ## to set specific fields. 
  def __init__(self, *args, **kwds):
    if args or kwds:
      super(CartesianArmServerActionGoal, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = roslib.msg._Header.Header()
      if self.goal_id is None:
        self.goal_id = actionlib_msgs.msg.GoalID()
      if self.goal is None:
        self.goal = cart_interp.msg.CartesianArmServerGoal()
    else:
      self.header = roslib.msg._Header.Header()
      self.goal_id = actionlib_msgs.msg.GoalID()
      self.goal = cart_interp.msg.CartesianArmServerGoal()

  ## internal API method
  def _get_types(self): return self._slot_types

  ## serialize message into buffer
  ## @param buff StringIO: buffer
  def serialize(self, buff):
    try:
      buff.write(struct.pack('<3I', self.header.seq, self.header.stamp.secs, self.header.stamp.nsecs))
      length = len(self.header.frame_id)
      #serialize self.header.frame_id
      buff.write(struct.pack('<I%ss'%length, length, self.header.frame_id))
      buff.write(struct.pack('<2I', self.goal_id.stamp.secs, self.goal_id.stamp.nsecs))
      length = len(self.goal_id.id)
      #serialize self.goal_id.id
      buff.write(struct.pack('<I%ss'%length, length, self.goal_id.id))
      buff.write(struct.pack('<3I', self.goal.setpoint.header.seq, self.goal.setpoint.header.stamp.secs, self.goal.setpoint.header.stamp.nsecs))
      length = len(self.goal.setpoint.header.frame_id)
      #serialize self.goal.setpoint.header.frame_id
      buff.write(struct.pack('<I%ss'%length, length, self.goal.setpoint.header.frame_id))
      buff.write(struct.pack('<7d', self.goal.setpoint.pose.position.x, self.goal.setpoint.pose.position.y, self.goal.setpoint.pose.position.z, self.goal.setpoint.pose.orientation.x, self.goal.setpoint.pose.orientation.y, self.goal.setpoint.pose.orientation.z, self.goal.setpoint.pose.orientation.w))
    except struct.error, se: self._check_types(se)
    except TypeError, te: self._check_types(te)

  ## unpack serialized message in str into this message instance
  ## @param self: self
  ## @param str str: byte array of serialized message
  def deserialize(self, str):
    try:
      if self.header is None:
        self.header = roslib.msg._Header.Header()
      if self.goal_id is None:
        self.goal_id = actionlib_msgs.msg.GoalID()
      if self.goal is None:
        self.goal = cart_interp.msg.CartesianArmServerGoal()
      end = 0
      start = end
      end += 12
      (self.header.seq, self.header.stamp.secs, self.header.stamp.nsecs,) = struct.unpack('<3I',str[start:end])
      start = end
      end += 4
      (length,) = struct.unpack('<I',str[start:end])
      #deserialize self.header.frame_id
      pattern = '<%ss'%length
      start = end
      end += struct.calcsize(pattern)
      (self.header.frame_id,) = struct.unpack(pattern, str[start:end])
      start = end
      end += 8
      (self.goal_id.stamp.secs, self.goal_id.stamp.nsecs,) = struct.unpack('<2I',str[start:end])
      start = end
      end += 4
      (length,) = struct.unpack('<I',str[start:end])
      #deserialize self.goal_id.id
      pattern = '<%ss'%length
      start = end
      end += struct.calcsize(pattern)
      (self.goal_id.id,) = struct.unpack(pattern, str[start:end])
      start = end
      end += 12
      (self.goal.setpoint.header.seq, self.goal.setpoint.header.stamp.secs, self.goal.setpoint.header.stamp.nsecs,) = struct.unpack('<3I',str[start:end])
      start = end
      end += 4
      (length,) = struct.unpack('<I',str[start:end])
      #deserialize self.goal.setpoint.header.frame_id
      pattern = '<%ss'%length
      start = end
      end += struct.calcsize(pattern)
      (self.goal.setpoint.header.frame_id,) = struct.unpack(pattern, str[start:end])
      start = end
      end += 56
      (self.goal.setpoint.pose.position.x, self.goal.setpoint.pose.position.y, self.goal.setpoint.pose.position.z, self.goal.setpoint.pose.orientation.x, self.goal.setpoint.pose.orientation.y, self.goal.setpoint.pose.orientation.z, self.goal.setpoint.pose.orientation.w,) = struct.unpack('<7d',str[start:end])
      return self
    except struct.error, e:
      raise roslib.message.DeserializationError(e) #most likely buffer underfill


  ## serialize message with numpy array types into buffer
  ## @param self: self
  ## @param buff StringIO: buffer
  ## @param numpy module: numpy python module
  def serialize_numpy(self, buff, numpy):
    try:
      buff.write(struct.pack('<3I', self.header.seq, self.header.stamp.secs, self.header.stamp.nsecs))
      length = len(self.header.frame_id)
      #serialize self.header.frame_id
      buff.write(struct.pack('<I%ss'%length, length, self.header.frame_id))
      buff.write(struct.pack('<2I', self.goal_id.stamp.secs, self.goal_id.stamp.nsecs))
      length = len(self.goal_id.id)
      #serialize self.goal_id.id
      buff.write(struct.pack('<I%ss'%length, length, self.goal_id.id))
      buff.write(struct.pack('<3I', self.goal.setpoint.header.seq, self.goal.setpoint.header.stamp.secs, self.goal.setpoint.header.stamp.nsecs))
      length = len(self.goal.setpoint.header.frame_id)
      #serialize self.goal.setpoint.header.frame_id
      buff.write(struct.pack('<I%ss'%length, length, self.goal.setpoint.header.frame_id))
      buff.write(struct.pack('<7d', self.goal.setpoint.pose.position.x, self.goal.setpoint.pose.position.y, self.goal.setpoint.pose.position.z, self.goal.setpoint.pose.orientation.x, self.goal.setpoint.pose.orientation.y, self.goal.setpoint.pose.orientation.z, self.goal.setpoint.pose.orientation.w))
    except struct.error, se: self._check_types(se)
    except TypeError, te: self._check_types(te)

  ## unpack serialized message in str into this message instance using numpy for array types
  ## @param self: self
  ## @param str str: byte array of serialized message
  ## @param numpy module: numpy python module
  def deserialize_numpy(self, str, numpy):
    try:
      if self.header is None:
        self.header = roslib.msg._Header.Header()
      if self.goal_id is None:
        self.goal_id = actionlib_msgs.msg.GoalID()
      if self.goal is None:
        self.goal = cart_interp.msg.CartesianArmServerGoal()
      end = 0
      start = end
      end += 12
      (self.header.seq, self.header.stamp.secs, self.header.stamp.nsecs,) = struct.unpack('<3I',str[start:end])
      start = end
      end += 4
      (length,) = struct.unpack('<I',str[start:end])
      #deserialize self.header.frame_id
      pattern = '<%ss'%length
      start = end
      end += struct.calcsize(pattern)
      (self.header.frame_id,) = struct.unpack(pattern, str[start:end])
      start = end
      end += 8
      (self.goal_id.stamp.secs, self.goal_id.stamp.nsecs,) = struct.unpack('<2I',str[start:end])
      start = end
      end += 4
      (length,) = struct.unpack('<I',str[start:end])
      #deserialize self.goal_id.id
      pattern = '<%ss'%length
      start = end
      end += struct.calcsize(pattern)
      (self.goal_id.id,) = struct.unpack(pattern, str[start:end])
      start = end
      end += 12
      (self.goal.setpoint.header.seq, self.goal.setpoint.header.stamp.secs, self.goal.setpoint.header.stamp.nsecs,) = struct.unpack('<3I',str[start:end])
      start = end
      end += 4
      (length,) = struct.unpack('<I',str[start:end])
      #deserialize self.goal.setpoint.header.frame_id
      pattern = '<%ss'%length
      start = end
      end += struct.calcsize(pattern)
      (self.goal.setpoint.header.frame_id,) = struct.unpack(pattern, str[start:end])
      start = end
      end += 56
      (self.goal.setpoint.pose.position.x, self.goal.setpoint.pose.position.y, self.goal.setpoint.pose.position.z, self.goal.setpoint.pose.orientation.x, self.goal.setpoint.pose.orientation.y, self.goal.setpoint.pose.orientation.z, self.goal.setpoint.pose.orientation.w,) = struct.unpack('<7d',str[start:end])
      return self
    except struct.error, e:
      raise roslib.message.DeserializationError(e) #most likely buffer underfill

