(defpackage recyclerbot-msg
  (:use cl
        roslisp-msg-protocol)
  (:export
   "<CYLINDER>"
   "<GRASPRESULT>"
   "<GRASPCLIENTFEEDBACK>"
   "<GRASPCLIENTGOAL>"
   "<GRASPACTION>"
   "<GRASPACTIONFEEDBACK>"
   "<GRASPCLIENTRESULT>"
   "<CYLINDERARRAY>"
   "<GRASPGOAL>"
   "<GRASPCLIENTACTION>"
   "<GRASPCLIENTACTIONFEEDBACK>"
   "<GRASPCLIENTACTIONRESULT>"
   "<GRASPCLIENTACTIONGOAL>"
   "<GRASPACTIONRESULT>"
   "<GRASPFEEDBACK>"
   "<GRASPACTIONGOAL>"
  ))

