; Auto-generated. Do not edit!


(in-package recyclerbot-msg)


;//! \htmlinclude GraspClientResult.msg.html

(defclass <GraspClientResult> (ros-message)
  ()
)
(defmethod serialize ((msg <GraspClientResult>) ostream)
  "Serializes a message object of type '<GraspClientResult>"
)
(defmethod deserialize ((msg <GraspClientResult>) istream)
  "Deserializes a message object of type '<GraspClientResult>"
  msg
)
(defmethod ros-datatype ((msg (eql '<GraspClientResult>)))
  "Returns string type for a message object of type '<GraspClientResult>"
  "recyclerbot/GraspClientResult")
(defmethod md5sum ((type (eql '<GraspClientResult>)))
  "Returns md5sum for a message object of type '<GraspClientResult>"
  "d41d8cd98f00b204e9800998ecf8427e")
(defmethod message-definition ((type (eql '<GraspClientResult>)))
  "Returns full string definition for message of type '<GraspClientResult>"
  (format nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%~%~%"))
(defmethod serialization-length ((msg <GraspClientResult>))
  (+ 0
))
(defmethod ros-message-to-list ((msg <GraspClientResult>))
  "Converts a ROS message object to a list"
  (list '<GraspClientResult>
))
