"""autogenerated by genmsg_py from WifiSniff.msg. Do not edit."""
import roslib.message
import struct

import roslib.rostime

class WifiSniff(roslib.message.Message):
  _md5sum = "3bed52c7a8a1d7cc0444e57a935d953a"
  _type = "wifi_sniffer/WifiSniff"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """time t
string mac
string ssid
int32 signal_level
int32 signal_noise

"""
  __slots__ = ['t','mac','ssid','signal_level','signal_noise']
  _slot_types = ['time','string','string','int32','int32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.
    
    The available fields are:
       t,mac,ssid,signal_level,signal_noise
    
    @param args: complete set of field values, in .msg order
    @param kwds: use keyword arguments corresponding to message field names
    to set specific fields. 
    """
    if args or kwds:
      super(WifiSniff, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.t is None:
        self.t = roslib.rostime.Time()
      if self.mac is None:
        self.mac = ''
      if self.ssid is None:
        self.ssid = ''
      if self.signal_level is None:
        self.signal_level = 0
      if self.signal_noise is None:
        self.signal_noise = 0
    else:
      self.t = roslib.rostime.Time()
      self.mac = ''
      self.ssid = ''
      self.signal_level = 0
      self.signal_noise = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    @param buff: buffer
    @type  buff: StringIO
    """
    try:
      _x = self
      buff.write(_struct_2I.pack(_x.t.secs, _x.t.nsecs))
      _x = self.mac
      length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self.ssid
      length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_2i.pack(_x.signal_level, _x.signal_noise))
    except struct.error, se: self._check_types(se)
    except TypeError, te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    @param str: byte array of serialized message
    @type  str: str
    """
    try:
      if self.t is None:
        self.t = roslib.rostime.Time()
      end = 0
      _x = self
      start = end
      end += 8
      (_x.t.secs, _x.t.nsecs,) = _struct_2I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.mac = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.ssid = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.signal_level, _x.signal_noise,) = _struct_2i.unpack(str[start:end])
      self.t.canon()
      return self
    except struct.error, e:
      raise roslib.message.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    @param buff: buffer
    @type  buff: StringIO
    @param numpy: numpy python module
    @type  numpy module
    """
    try:
      _x = self
      buff.write(_struct_2I.pack(_x.t.secs, _x.t.nsecs))
      _x = self.mac
      length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self.ssid
      length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_2i.pack(_x.signal_level, _x.signal_noise))
    except struct.error, se: self._check_types(se)
    except TypeError, te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    @param str: byte array of serialized message
    @type  str: str
    @param numpy: numpy python module
    @type  numpy: module
    """
    try:
      if self.t is None:
        self.t = roslib.rostime.Time()
      end = 0
      _x = self
      start = end
      end += 8
      (_x.t.secs, _x.t.nsecs,) = _struct_2I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.mac = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.ssid = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.signal_level, _x.signal_noise,) = _struct_2i.unpack(str[start:end])
      self.t.canon()
      return self
    except struct.error, e:
      raise roslib.message.DeserializationError(e) #most likely buffer underfill

_struct_I = roslib.message.struct_I
_struct_2I = struct.Struct("<2I")
_struct_2i = struct.Struct("<2i")
